# Generated by Django 2.2 on 2020-01-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20191231_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='img',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
