# Generated by Django 2.2 on 2020-01-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_art_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='stripe_charge_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
