# Generated by Django 2.2 on 2020-01-03 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_userprofile_one_click_purchasing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
