# Generated by Django 2.2 on 2020-01-03 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
