# Generated by Django 2.2 on 2019-12-31 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_art_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='art',
            options={'verbose_name_plural': 'Artwork'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='items',
            new_name='art',
        ),
    ]
